name: yt-scraper
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - pip:
    - dataclasses_json
    - python-youtube
    - git+https://github.com/nimaid/youtube-transcript-api.git@add-caption-type-option
